eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8801
spring:
  application:
    name: service-api-gateway
  zipkin:
    base-url: http://172.16.2.176:9411
  sleuth:
    sampler:
      percentage: 1
zuul:
  routes:
    api-order:
      path: /api-order/**
      serviceId: service-order
