eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8801
spring:
  application:
    name: service-api-gateway
  zipkin:
    base-url: http://peer1:9411
  sleuth:
    sampler:
      percentage: 1
zuul:
  routes:
    api-order:
      path: /api-order/**
      serviceId: service-order
